version: '3.8'

services:
  jenkins:
    image: jenkins/jenkins:jdk17
    container_name: jenkins
    privileged: true
    user: root
    ports:
      - "8080:8080"
      - "50000:50000"
    volumes:
      - jenkins_data:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
      - /usr/bin/git:/usr/bin/git:ro  # Добавляем Git с хоста
      - /usr/libexec/git-core:/usr/libexec/git-core:ro  # Необходимо для работы Git
    environment:
      - JAVA_OPTS=-Dhudson.plugins.git.GitSCM.ALLOW_LOCAL_CHECKOUT=true
    command: >
      bash -c "
      chmod 777 /var/run/docker.sock &&
      /usr/local/bin/jenkins.sh
      "
    depends_on:
      - dind

  dind:
    image: docker:dind
    container_name: jenkins-dind
    privileged: true
    environment:
      - DOCKER_TLS_CERTDIR=
    command: ["dockerd", "--host=tcp://0.0.0.0:2375", "--host=unix:///var/run/docker.sock"]
    volumes:
      - dind_data:/var/lib/docker

volumes:
  jenkins_data:
  dind_data:
